# https://golangci-lint.run/usage/configuration/
run:
  timeout: 2m

output:
  format: tab

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - dupl
    - depguard
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - misspell
    - unconvert

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - "github.com/gookit/color" # no longer maintained
          - "github.com/kr/pretty" # no longer maintained
